### ISSUE TITLE
Examine All User Stories

### ISSUE THREAD

**Issue by ez4bk** [ez4bk/smarter-university-system-17#17]
Activity of Epic #44 
Examine all user stories created. Eliminate unnecessary ones and optimize the best outcome.

**Comment by varungole** [comment]
@ez4bk please verify the requirements once again to check if they are following the format. (Hopefully) I've fixed all of them

**Comment by ez4bk** [comment]
> @ez4bk please verify the requirements once again to check if they are following the format. (Hopefully) I've fixed all of them 

will do

**Comment by varungole** [comment]
Hi, I have added more requirements. Please verify the requirements again and check if we missed any requirement written in the SOW. If yes. please add them in the excel sheet. Please do this very urgently so that we can start on the binary tree and prioritzation and get done with the first part today itself :)

**Comment by ez4bk** [comment]
All requirements/user stories are refined according to SOW. More may be added or updated later. Closing the ticket.
